# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='hello.proto',
  package='relay',
  serialized_pb='\n\x0bhello.proto\x12\x05relay\"\x17\n\x15\x43lientHelloProperties\"\x1c\n\x1aHostProcessHelloProperties\"\xe8\x01\n\x05Hello\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12(\n\tpeer_type\x18\x02 \x02(\x0e\x32\x15.relay.Hello.PeerType\x12\x37\n\x11\x63lient_properties\x18\x03 \x01(\x0b\x32\x1c.relay.ClientHelloProperties\x12\x41\n\x16hostprocess_properties\x18\x04 \x01(\x0b\x32!.relay.HostProcessHelloProperties\"(\n\x08PeerType\x12\n\n\x06\x43LIENT\x10\x00\x12\x10\n\x0cHOST_PROCESS\x10\x01\"\'\n\x13\x43lientHelloResponse\x12\x10\n\x08\x61ssigned\x18\x01 \x02(\x08\"V\n\x18HostProcessHelloResponse\x12\x12\n\nsession_id\x18\x01 \x02(\x05\x12\x12\n\nrelay_host\x18\x02 \x02(\t\x12\x12\n\nrelay_port\x18\x03 \x02(\t')



_HELLO_PEERTYPE = descriptor.EnumDescriptor(
  name='PeerType',
  full_name='relay.Hello.PeerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='CLIENT', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='HOST_PROCESS', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=270,
  serialized_end=310,
)


_CLIENTHELLOPROPERTIES = descriptor.Descriptor(
  name='ClientHelloProperties',
  full_name='relay.ClientHelloProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=45,
)


_HOSTPROCESSHELLOPROPERTIES = descriptor.Descriptor(
  name='HostProcessHelloProperties',
  full_name='relay.HostProcessHelloProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=47,
  serialized_end=75,
)


_HELLO = descriptor.Descriptor(
  name='Hello',
  full_name='relay.Hello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='relay.Hello.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='peer_type', full_name='relay.Hello.peer_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='client_properties', full_name='relay.Hello.client_properties', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hostprocess_properties', full_name='relay.Hello.hostprocess_properties', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HELLO_PEERTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=78,
  serialized_end=310,
)


_CLIENTHELLORESPONSE = descriptor.Descriptor(
  name='ClientHelloResponse',
  full_name='relay.ClientHelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='assigned', full_name='relay.ClientHelloResponse.assigned', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=312,
  serialized_end=351,
)


_HOSTPROCESSHELLORESPONSE = descriptor.Descriptor(
  name='HostProcessHelloResponse',
  full_name='relay.HostProcessHelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='session_id', full_name='relay.HostProcessHelloResponse.session_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='relay_host', full_name='relay.HostProcessHelloResponse.relay_host', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='relay_port', full_name='relay.HostProcessHelloResponse.relay_port', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=353,
  serialized_end=439,
)

_HELLO.fields_by_name['peer_type'].enum_type = _HELLO_PEERTYPE
_HELLO.fields_by_name['client_properties'].message_type = _CLIENTHELLOPROPERTIES
_HELLO.fields_by_name['hostprocess_properties'].message_type = _HOSTPROCESSHELLOPROPERTIES
_HELLO_PEERTYPE.containing_type = _HELLO;
DESCRIPTOR.message_types_by_name['ClientHelloProperties'] = _CLIENTHELLOPROPERTIES
DESCRIPTOR.message_types_by_name['HostProcessHelloProperties'] = _HOSTPROCESSHELLOPROPERTIES
DESCRIPTOR.message_types_by_name['Hello'] = _HELLO
DESCRIPTOR.message_types_by_name['ClientHelloResponse'] = _CLIENTHELLORESPONSE
DESCRIPTOR.message_types_by_name['HostProcessHelloResponse'] = _HOSTPROCESSHELLORESPONSE

class ClientHelloProperties(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLIENTHELLOPROPERTIES
  
  # @@protoc_insertion_point(class_scope:relay.ClientHelloProperties)

class HostProcessHelloProperties(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HOSTPROCESSHELLOPROPERTIES
  
  # @@protoc_insertion_point(class_scope:relay.HostProcessHelloProperties)

class Hello(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HELLO
  
  # @@protoc_insertion_point(class_scope:relay.Hello)

class ClientHelloResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLIENTHELLORESPONSE
  
  # @@protoc_insertion_point(class_scope:relay.ClientHelloResponse)

class HostProcessHelloResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HOSTPROCESSHELLORESPONSE
  
  # @@protoc_insertion_point(class_scope:relay.HostProcessHelloResponse)

# @@protoc_insertion_point(module_scope)
